export const AuthActionTypes = {
    AUTH_START: "AUTH_START",
    AUTH_SUCCESS: "AUTH_SUCCESS",
    AUTH_FAIL: "AUTH_FAIL"
}

export const PostActionTypes = {
    UPLOAD_START: "UPLOAD_START",
    UPLOAD_SUCCESS: "UPLOAD_SUCCESS",
    UPLOAD_FAIL: "UPLOAD_FAIL"
}

export const GetTimelinePostActionTypes = {
    RETREIVING_START: "RETREIVING_START",
    RETREIVING_SUCCESS: "RETREIVING_SUCCESS",
    RETREIVING_FAIL: "RETREIVING_FAIL",
}